tracker:
    image: anthonyzou/opentracker:latest
    container_name: local-p2p-tracker
    restart: always
    ports:
      # Note: Ports are open locally but secured by the lab's Zero-Trust architecture and Tailscale.
      # Access is restricted to authorized nodes within the sovereign mesh network
      - 6969:6969/udp
      - 6969:6969/tcp
networks: {}
